"""
DSSMS Phase 3 Task 3.3: 検証結果レポーター
自動検証フレームワークの結果レポート生成

Author: GitHub Copilot Agent
Created: 2025-08-28
Phase: 3 Task 3.3
"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional
import pandas as pd

# プロジェクトルートを追加
project_root = Path(__file__).parent.parent.parent
sys.path.append(str(project_root))

from src.testing.dssms_validation_framework import ValidationResult, ValidationLevel, ValidationConfig
from config.logger_config import setup_logger

class ValidationReporter:
    """検証結果レポート生成器"""
    
    def __init__(self, config: ValidationConfig, logger=None):
        """
        初期化
        
        Args:
            config: 検証設定
            logger: ロガー
        """
        self.config = config
        self.logger = logger or setup_logger("ValidationReporter")
        self.project_root = project_root
        self.output_dir = self.project_root / "output" / "validation_reports"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def generate_report(self, results: List[ValidationResult], output_path: Optional[str] = None) -> str:
        """
        検証結果レポート生成
        
        Args:
            results: 検証結果リスト
            output_path: 出力ファイルパス
            
        Returns:
            生成されたレポートファイルパス
        """
        try:
            if output_path is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                output_path = self.output_dir / f"dssms_validation_report_{timestamp}.html"
            
            # HTMLレポート生成
            html_content = self._generate_html_report(results)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            # JSON形式でも保存
            json_path = str(output_path).replace('.html', '.json')
            self._save_json_report(results, json_path)
            
            # Excelレポートも生成
# TODO(tag:excel_deprecated, rationale:Excel output eliminated 2025-10-08) # BACKTEST_IMPACT: Trading data output affected
# ORIGINAL: excel_path = str(output_path).replace('.html', '.xlsx')
            self._generate_excel_report(results, excel_path)
            
            self.logger.info(f"検証レポート生成完了: {output_path}")
            return str(output_path)
            
        except Exception as e:
            self.logger.error(f"レポート生成エラー: {e}")
            return ""
    
    def _generate_html_report(self, results: List[ValidationResult]) -> str:
        """HTMLレポート生成"""
        # 結果サマリー計算
        summary = self._calculate_summary(results)
        
        # HTMLテンプレート
        html_template = f"""
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DSSMS 自動検証レポート</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>DSSMS 自動検証レポート</h1>
            <p class="timestamp">生成日時: {datetime.now().strftime('%Y年%m月%d日 %H:%M:%S')}</p>
        </header>
        
        <section class="summary">
            {self._generate_summary_section(summary)}
        </section>
        
        <section class="detailed-results">
            {self._generate_detailed_section(results)}
        </section>
        
        <section class="recommendations">
            {self._generate_recommendations_section(results)}
        </section>
        
        <footer>
            <p>DSSMS Phase 3 Task 3.3: 自動検証フレームワーク</p>
            <p>Generated by GitHub Copilot Agent</p>
        </footer>
    </div>
</body>
</html>
"""
        return html_template
    
    def _calculate_summary(self, results: List[ValidationResult]) -> Dict[str, Any]:
        """結果サマリー計算"""
        if not results:
            return {'total': 0, 'success': 0, 'failed': 0, 'overall_score': 0.0}
        
        total = len(results)
        success = sum(1 for r in results if r.success)
        failed = total - success
        overall_score = sum(r.score for r in results) / total
        
        # レベル別サマリー
        level_summary = {}
        for level in ValidationLevel:
            level_results = [r for r in results if r.level == level]
            if level_results:
                level_summary[level.value] = {
                    'count': len(level_results),
                    'success': sum(1 for r in level_results if r.success),
                    'avg_score': sum(r.score for r in level_results) / len(level_results)
                }
        
        # エラー・警告集計
        all_errors = []
        all_warnings = []
        for result in results:
            all_errors.extend(result.errors)
            all_warnings.extend(result.warnings)
        
        return {
            'total': total,
            'success': success,
            'failed': failed,
            'success_rate': success / total,
            'overall_score': overall_score,
            'level_summary': level_summary,
            'total_errors': len(all_errors),
            'total_warnings': len(all_warnings),
            'unique_errors': len(set(all_errors)),
            'unique_warnings': len(set(all_warnings))
        }
    
    def _generate_summary_section(self, summary: Dict[str, Any]) -> str:
        """サマリーセクション生成"""
        success_rate = summary['success_rate']
        overall_score = summary['overall_score']
        
        # ステータス判定
        if success_rate >= 0.9 and overall_score >= 0.85:
            status = "優秀"
            status_class = "excellent"
        elif success_rate >= 0.8 and overall_score >= 0.75:
            status = "良好"
            status_class = "good"
        elif success_rate >= 0.6 and overall_score >= 0.60:
            status = "要改善"
            status_class = "needs-improvement"
        else:
            status = "要修正"
            status_class = "needs-fix"
        
        html = f"""
        <h2>検証結果サマリー</h2>
        <div class="summary-grid">
            <div class="summary-card {status_class}">
                <h3>総合ステータス</h3>
                <p class="big-text">{status}</p>
                <p>スコア: {overall_score:.1%}</p>
            </div>
            
            <div class="summary-card">
                <h3>検証実行結果</h3>
                <p>成功: {summary['success']}/{summary['total']} ({success_rate:.1%})</p>
                <p>失敗: {summary['failed']} 件</p>
            </div>
            
            <div class="summary-card">
                <h3>問題発見状況</h3>
                <p>エラー: {summary['total_errors']} 件</p>
                <p>警告: {summary['total_warnings']} 件</p>
            </div>
        </div>
        
        <div class="level-breakdown">
            <h3>レベル別結果</h3>
            <table>
                <thead>
                    <tr>
                        <th>検証レベル</th>
                        <th>実行数</th>
                        <th>成功数</th>
                        <th>成功率</th>
                        <th>平均スコア</th>
                    </tr>
                </thead>
                <tbody>
"""
        
        for level_name, level_data in summary['level_summary'].items():
            success_rate = level_data['success'] / level_data['count']
            avg_score = level_data['avg_score']
            
            html += f"""
                    <tr>
                        <td>{level_name}</td>
                        <td>{level_data['count']}</td>
                        <td>{level_data['success']}</td>
                        <td>{success_rate:.1%}</td>
                        <td>{avg_score:.1%}</td>
                    </tr>
"""
        
        html += """
                </tbody>
            </table>
        </div>
        """
        
        return html
    
    def _generate_detailed_section(self, results: List[ValidationResult]) -> str:
        """詳細結果セクション生成"""
        html = """
        <h2>詳細検証結果</h2>
        """
        
        for result in results:
            status_class = "success" if result.success else "failure"
            
            html += f"""
            <div class="result-card {status_class}">
                <h3>{result.level.value.title()} Validation - {result.test_name}</h3>
                <div class="result-meta">
                    <span>実行時刻: {result.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</span>
                    <span>実行時間: {result.execution_time:.2f}秒</span>
                    <span>スコア: {result.score:.1%}</span>
                    <span class="status">{'成功' if result.success else '失敗'}</span>
                </div>
                
                {self._format_result_details(result)}
                
                {self._format_errors_warnings(result)}
            </div>
            """
        
        return html
    
    def _format_result_details(self, result: ValidationResult) -> str:
        """結果詳細のフォーマット"""
        if not result.details:
            return ""
        
        html = "<div class=\"result-details\"><h4>詳細情報</h4><ul>"
        
        for key, value in result.details.items():
            if isinstance(value, dict):
                html += f"<li><strong>{key}:</strong><ul>"
                for sub_key, sub_value in value.items():
                    html += f"<li>{sub_key}: {sub_value}</li>"
                html += "</ul></li>"
            else:
                html += f"<li><strong>{key}:</strong> {value}</li>"
        
        html += "</ul></div>"
        return html
    
    def _format_errors_warnings(self, result: ValidationResult) -> str:
        """エラー・警告のフォーマット"""
        html = ""
        
        if result.errors:
            html += "<div class=\"errors\"><h4>エラー</h4><ul>"
            for error in result.errors:
                html += f"<li>{error}</li>"
            html += "</ul></div>"
        
        if result.warnings:
            html += "<div class=\"warnings\"><h4>警告</h4><ul>"
            for warning in result.warnings:
                html += f"<li>{warning}</li>"
            html += "</ul></div>"
        
        if result.suggestions:
            html += "<div class=\"suggestions\"><h4>改善提案</h4><ul>"
            for suggestion in result.suggestions:
                html += f"<li>{suggestion}</li>"
            html += "</ul></div>"
        
        return html
    
    def _generate_recommendations_section(self, results: List[ValidationResult]) -> str:
        """推奨事項セクション生成"""
        # 全ての提案を収集
        all_suggestions = []
        priority_issues = []
        
        for result in results:
            all_suggestions.extend(result.suggestions)
            if not result.success or result.score < 0.7:
                priority_issues.append({
                    'level': result.level.value,
                    'score': result.score,
                    'errors': result.errors,
                    'suggestions': result.suggestions
                })
        
        # 優先度付き推奨事項
        html = """
        <h2>推奨事項</h2>
        """
        
        if priority_issues:
            html += """
            <div class="priority-issues">
                <h3>優先対応事項</h3>
            """
            
            for issue in priority_issues:
                html += f"""
                <div class="priority-issue">
                    <h4>{issue['level']} (スコア: {issue['score']:.1%})</h4>
                    <ul>
                """
                for suggestion in issue['suggestions']:
                    html += f"<li>{suggestion}</li>"
                html += "</ul></div>"
            
            html += "</div>"
        
        # 一般的な改善提案
        if all_suggestions:
            unique_suggestions = list(set(all_suggestions))
            html += """
            <div class="general-recommendations">
                <h3>一般的な改善提案</h3>
                <ul>
            """
            for suggestion in unique_suggestions:
                html += f"<li>{suggestion}</li>"
            html += "</ul></div>"
        
        return html
    
    def _get_css_styles(self) -> str:
        """CSSスタイル定義"""
        return """
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            color: #333;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        header {
            text-align: center;
            border-bottom: 2px solid #007acc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        h1 {
            color: #007acc;
            margin: 0;
        }
        
        .timestamp {
            color: #666;
            margin: 10px 0 0 0;
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .summary-card {
            padding: 20px;
            border-radius: 8px;
            background-color: #f8f9fa;
            border-left: 4px solid #007acc;
        }
        
        .summary-card.excellent {
            border-left-color: #28a745;
            background-color: #d4edda;
        }
        
        .summary-card.good {
            border-left-color: #007acc;
            background-color: #d1ecf1;
        }
        
        .summary-card.needs-improvement {
            border-left-color: #ffc107;
            background-color: #fff3cd;
        }
        
        .summary-card.needs-fix {
            border-left-color: #dc3545;
            background-color: #f8d7da;
        }
        
        .big-text {
            font-size: 24px;
            font-weight: bold;
            margin: 10px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        
        th {
            background-color: #007acc;
            color: white;
        }
        
        .result-card {
            margin: 20px 0;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #ddd;
        }
        
        .result-card.success {
            border-left: 4px solid #28a745;
            background-color: #f8fff9;
        }
        
        .result-card.failure {
            border-left: 4px solid #dc3545;
            background-color: #fff8f8;
        }
        
        .result-meta {
            display: flex;
            gap: 20px;
            margin: 10px 0;
            font-size: 14px;
            color: #666;
        }
        
        .status {
            font-weight: bold;
        }
        
        .errors {
            background-color: #f8d7da;
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
        }
        
        .warnings {
            background-color: #fff3cd;
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
        }
        
        .suggestions {
            background-color: #d1ecf1;
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
        }
        
        .priority-issue {
            background-color: #fff3cd;
            padding: 15px;
            border-radius: 4px;
            margin: 10px 0;
            border-left: 4px solid #ffc107;
        }
        
        footer {
            text-align: center;
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 14px;
        }
        """
    
    def _save_json_report(self, results: List[ValidationResult], output_path: str):
        """JSON形式でレポート保存"""
        try:
            json_data = {
                'timestamp': datetime.now().isoformat(),
                'summary': self._calculate_summary(results),
                'results': []
            }
            
            for result in results:
                json_data['results'].append({
                    'level': result.level.value,
                    'test_name': result.test_name,
                    'timestamp': result.timestamp.isoformat(),
                    'success': result.success,
                    'execution_time': result.execution_time,
                    'score': result.score,
                    'details': result.details,
                    'errors': result.errors,
                    'warnings': result.warnings,
                    'suggestions': result.suggestions
                })
            
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(json_data, f, indent=2, ensure_ascii=False)
                
        except Exception as e:
            self.logger.warning(f"JSON レポート保存エラー: {e}")
    
    def _generate_excel_report(self, results: List[ValidationResult], output_path: str):
        """Excelレポート生成"""
        try:
# TODO(tag:excel_deprecated, rationale:Excel output eliminated 2025-10-08) # BACKTEST_IMPACT: Trading data output affected
# ORIGINAL: with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
                # サマリーシート
                summary = self._calculate_summary(results)
                summary_df = pd.DataFrame([summary])
# TODO(tag:excel_deprecated, rationale:Excel output eliminated 2025-10-08) # BACKTEST_IMPACT: Trading data output affected
# ORIGINAL: summary_df.to_excel(writer, sheet_name='Summary', index=False)
                
                # 詳細結果シート
                results_data = []
                for result in results:
                    results_data.append({
                        'Level': result.level.value,
                        'Test Name': result.test_name,
                        'Timestamp': result.timestamp,
                        'Success': result.success,
                        'Execution Time': result.execution_time,
                        'Score': result.score,
                        'Errors Count': len(result.errors),
                        'Warnings Count': len(result.warnings),
                        'Suggestions Count': len(result.suggestions)
                    })
                
                results_df = pd.DataFrame(results_data)
# TODO(tag:excel_deprecated, rationale:Excel output eliminated 2025-10-08) # BACKTEST_IMPACT: Trading data output affected
# ORIGINAL: results_df.to_excel(writer, sheet_name='Results', index=False)
                
                # エラー・警告シート
                issues_data = []
                for result in results:
                    for error in result.errors:
                        issues_data.append({
                            'Level': result.level.value,
                            'Type': 'Error',
                            'Message': error
                        })
                    for warning in result.warnings:
                        issues_data.append({
                            'Level': result.level.value,
                            'Type': 'Warning',
                            'Message': warning
                        })
                
                if issues_data:
                    issues_df = pd.DataFrame(issues_data)
# TODO(tag:excel_deprecated, rationale:Excel output eliminated 2025-10-08) # BACKTEST_IMPACT: Trading data output affected
# ORIGINAL: issues_df.to_excel(writer, sheet_name='Issues', index=False)
                
        except Exception as e:
            self.logger.warning(f"Excel レポート生成エラー: {e}")

if __name__ == "__main__":
    # テスト実行
    from src.testing.dssms_validation_framework import ValidationConfig
    
    logger = setup_logger("ValidationReporterTest")
    config = ValidationConfig(
        validation_levels=[],
        parallel_execution=False,
        early_termination=False,
        auto_fix_attempts=3,
        high_level_criteria={},
        timeout_seconds=300,
        log_level="INFO"
    )
    
    # サンプル結果作成
    sample_results = [
        ValidationResult(
            level=ValidationLevel.BASIC,
            test_name="basic_test",
            timestamp=datetime.now(),
            success=True,
            execution_time=1.5,
            score=0.85,
            details={"import_check": 0.9, "config_check": 0.8},
            errors=[],
            warnings=["設定ファイルが1つ見つかりません"],
            suggestions=["設定ファイルパスを確認してください"]
        ),
        ValidationResult(
            level=ValidationLevel.PERFORMANCE,
            test_name="performance_test",
            timestamp=datetime.now(),
            success=False,
            execution_time=10.2,
            score=0.65,
            details={"total_return": 0.05, "sharpe_ratio": 1.2},
            errors=["パフォーマンス基準を満たしていません"],
            warnings=[],
            suggestions=["ポートフォリオ構成を見直してください"]
        )
    ]
    
    reporter = ValidationReporter(config, logger)
    report_path = reporter.generate_report(sample_results)
    
    print(f"テストレポート生成完了: {report_path}")
